### ISSUE TITLE
Investigate use of DS/Map

### ISSUE THREAD

**Issue by stu-greenshoots** [opendialogai/core#165]
We use DS\Map extensively in the package and it is causing a performance issue.

```
        $array = [];
        for ($i=0;$i<10000;$i++) {
            if (!isset($array[$i])) {
                $array[$i] = $i;
            }
        }
```

The above runs in 0.000352 seconds

The below runs in 6.683 seconds

```
        $map = new Map();
        for ($i=0;$i<10000;$i++) {
            if (!$map->hasKey($i)) {
                $map->put($i, $i);
            }
        }
```

Maps might have their place, but we are not using any features that do not already exist in arrays and the performance hit is noticeable with complex conversations

**Comment by elliotmassen** [comment]
This came back to mind recently. I wonder if we could profile an average OpenDialog application and determine if this (alongside the DGraph client) is the cause of slow tests and responses. This _could_ be a great performance win to get into one of the coming minor versions. (cc. @istos @stu-greenshoots)
