### ISSUE TITLE
Invalid characters in dgraph queries

### ISSUE THREAD

**Issue by stu-greenshoots** [opendialogai/core#172]
When trying to save a conversation that contains a star (*) the triple mutation fails with the following error:

    0 => array:2 [▼
      "code" => "ErrorInvalidRequest"
      "message" => "while lexing _:a_level_confirm <has_expected_attribute> _:user.a* .: Invalid character '*' found for itemType: 8"
    ]

OpenDialogAi\Core\Graph\DGraph\DGraphMutationResponse __construct
…/vendor/opendialogai/core/src/Graph/DGraph/DGraphClient.php81

**Comment by nicolocaruso85** [comment]
https://github.com/opendialogai/core/pull/195
