### ISSUE TITLE
getAttributeValue doesn't gracefully handle empty attributes

### ISSUE THREAD

**Issue by duncanheron** [opendialogai/core#302]
Calling `ContextService::getUserContext()->getAttributeValue('nonexistentvalue')` when an attribute doesnt exists currently throws a fatal error

**Comment by stu-greenshoots** [comment]
This issue is still open as we are seeing issues on the user context with getting attribute values directly always returning null

**Comment by stu-greenshoots** [comment]
https://github.com/opendialogai/core/issues/318
